services:
  hello-world:
    image: ${IMAGE:-ghcr.io/pradtke-dev/hello-world/pradtke-hello-world:candidate}
    ports:
      - "80:80"
    links:
      - sql-db
    depends_on:
      - sql-db
    profiles:
      - production
      - test
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
  sql-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql-db
    environment:
      - SA_PASSWORD=yourStrong(!)Password
      - ACCEPT_EULA=Y
    profiles:
      - production
      - test
  sql-db-dev:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql-db
    environment:
      - SA_PASSWORD=yourStrong(!)Password
      - ACCEPT_EULA=Y
    ports: 
      - "1433:1433"
    profiles:
      - development
    
