name: Build and Deploy to Azure

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  CANDIDATE: ghcr.io/${{ github.repository }}/pradtke-hello-world:candidate
  LATEST_TAG_APP: ghcr.io/${{ github.repository }}/pradtke-hello-world:${{ github.run_number }}

jobs:
  build:
    runs-on: self-hosted
    permissions:
      contents: read
      packages: write
    defaults:
      run:
        working-directory: App

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0.x'

    - name: Cache .NET packages
      uses: actions/cache@v3
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/csproj') }}
        restore-keys: |
          ${{ runner.os }}-nuget-

    - name: Install dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Publish
      run: dotnet publish --configuration Release --no-build --output ./publish

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Build and push Docker image
      run: |
        docker build -t ${{ env.CANDIDATE }} .
        docker push ${{ env.CANDIDATE }}
    
  test:
    runs-on: self-hosted
    needs: build
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Start container
      run: |
        $env:IMAGE=$env:CANDIDATE
        $env:ASPNETCORE_ENVIRONMENT="Test"
        docker compose --profile test up -d

    - name: Run migrations
      run: |
        docker cp App/Scripts/up.sql sql-db:/tmp/migration.sql
        docker exec -i sql-db /opt/mssql-tools18/bin/sqlcmd -C -S localhost -U sa -P 'yourStrong(!)Password' -i /tmp/migration.sql

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: integration-tests/package-lock.json
    
    - name: Run integration tests
      run: |
        pushd integration-tests
        npm install
        npx cypress run
        popd

    - name: verify
      if: failure()
      run: docker compose --profile test logs -n 1000

    - name: Upload Cypress artifacts
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: cypress-artifacts
        path: |
          integration-tests/cypress/screenshots
          integration-tests/cypress/videos

    - name: Tag container as latest    
      if: success()
      run: |
        docker tag $env:CANDIDATE $env:LATEST_TAG_APP
        docker push $env:LATEST_TAG_APP

  deploy:
    runs-on: self-hosted
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Docker Compose
        run: |
          $env:IMAGE=$env:LATEST_TAG_APP
          $env:ASPNETCORE_ENVIRONMENT="Production"
          docker compose --profile production up -d
